#!/bin/bash
#PBS -l select=1:ncpus=16:mem=96gb:ngpus=1:gpu_type=RTX6000:cpu_type=rome
#PBS -l walltime=72:00:00
cd /rds/general/user/zf1415/home/FZY/llm/llm_math_reasoning/applications/DeepSpeed-Chat/training/step1_supervised_finetuning
module load anaconda3/personal
source activate llmmath 
python prompt_eval_math.py  --model_name_or_path_finetune llama2_7b_baseline_bs8_gs8_fp16/ >test_baseline_bs8_gs8_fp16.log 2>&1